### ISSUE TITLE
Ability to set app name per site

### ISSUE THREAD

**Issue by jmcgaha** [TopShelfCraft/New-Relic#3]
We have a multi-site install and before adding this plugin we were getting results for each site as a separate app in New Relic.
After adding the plugin we are only getting results in the app whose name matches the app name we put in the settings area for the plugin. (If we leave the plugin settings blank it just made a generic PHP application app in New Relic).

Would there be a way to specify the app name per site?

**Comment by michaelrog** [comment]
Sure, you can add a plugin config file (`new-relic.php`), and set the `appName` setting using [multi-env config syntax or environment variables](https://docs.craftcms.com/v3/config/environments.html#control-panel-settings).

**Comment by jmcgaha** [comment]
Awesome idea. Thank you!
