### ISSUE TITLE
Unresolved route Exception causes Codeception unit tests to fail

### ISSUE THREAD

**Issue by renzoolguin** [TopShelfCraft/New-Relic#7]
@michaelrog , we noticed that having this plugin enabled was causing our unit and API tests to fail with the following error. 

```sh
Codeception PHP Testing Framework v4.1.22
Powered by PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

In Request.php line 1326:
                                   
  [yii\web\NotFoundHttpException]  
  Page not found.                  
                                   

Exception trace:
  at /app/vendor/craftcms/cms/src/web/Request.php:1326
 craft\web\Request->resolve() at /app/vendor/topshelfcraft/new-relic/src/NewRelic.php:68
 topshelfcraft\newrelic\NewRelic->init() at /app/vendor/yiisoft/yii2/base/BaseObject.php:109
 yii\base\BaseObject->__construct() at /app/vendor/yiisoft/yii2/base/Module.php:158
 yii\base\Module->__construct() at /app/vendor/craftcms/cms/src/base/Plugin.php:115
 craft\base\Plugin->__construct() at n/a:n/a
 ReflectionClass->newInstanceArgs() at /app/vendor/yiisoft/yii2/di/Container.php:420
 yii\di\Container->build() at /app/vendor/yiisoft/yii2/di/Container.php:171
 yii\di\Container->get() at /app/vendor/yiisoft/yii2/BaseYii.php:365
 yii\BaseYii::createObject() at /app/vendor/craftcms/cms/src/Craft.php:67
 Craft::createObject() at /app/vendor/craftcms/cms/src/services/Plugins.php:981
 craft\services\Plugins->createPlugin() at /app/vendor/craftcms/cms/src/services/Plugins.php:233
 craft\services\Plugins->loadPlugins() at /app/vendor/craftcms/cms/src/services/Plugins.php:473
 craft\services\Plugins->installPlugin() at /app/vendor/craftcms/cms/src/test/Craft.php:294
 craft\test\Craft->installPlugin() at /app/vendor/craftcms/cms/src/test/Craft.php:267
 craft\test\Craft->setupDb() at /app/vendor/craftcms/cms/src/test/Craft.php:134
 craft\test\Craft->_beforeSuite() at /app/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:38
 Codeception\Subscriber\Module->beforeSuite() at /app/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at /app/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /app/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php:22
 Codeception\SuiteManager->dispatch() at /app/vendor/codeception/codeception/src/Codeception/SuiteManager.php:159
 Codeception\SuiteManager->run() at /app/vendor/codeception/codeception/src/Codeception/Codecept.php:208
 Codeception\Codecept->runSuite() at /app/vendor/codeception/codeception/src/Codeception/Codecept.php:162
 Codeception\Codecept->run() at /app/vendor/codeception/codeception/src/Codeception/Command/Run.php:532
 Codeception\Command\Run->runSuites() at /app/vendor/codeception/codeception/src/Codeception/Command/Run.php:407
 Codeception\Command\Run->execute() at /app/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:1005
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /app/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at /app/vendor/codeception/codeception/app.php:46
 {closure}() at /app/vendor/codeception/codeception/app.php:47
 require() at /app/vendor/codeception/codeception/codecept:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]


COMMAND DID NOT FINISH PROPERLY.
```

The error is triggered here, https://github.com/craftcms/cms/blob/develop/src/web/Request.php#L1325 where  `Craft::$app->getUrlManager()->parseRequest($this))` resolves to `false`. I quick fix, not sure if the correct fix, would be to wrap 
https://github.com/TopShelfCraft/New-Relic/blob/master/src/NewRelic.php#L68 in a try-catch. 

```php
try {
    $route = $request->resolve();
}
catch (\yii\web\NotFoundHttpException $e) {
    /*
     * Page not found error when
     * Craft::$app->getUrlManager()->parseRequest($request) is false
     */

    $route = "page-not-found";
}

$name = "Console/{$route}";
```

Let me know if you would prefer that I make a PR or better yet if I simply forgot to set a configuration.

**Comment by michaelrog** [comment]
Thanks for investigating this, @renzoolguin!

I'm a bit confused, though... By the time we get to [L68](https://github.com/TopShelfCraft/New-Relic/blob/555a6b48dd235b89bc5362f278e02b5212ea5989/src/NewRelic.php#L68), in that snippet, we're in a branch where `$request->getIsConsoleRequest()` returns true, so `$request` should be an instance of the *_console_* Request object (`yii\console\Request`). How then is `$request->resolve()` throwing a *_web_*-related error? I assume this has to do with the testing setup... Do you understand what's going on there?

(I acknowledge that your quick-fix will silence the error and allow your tests to complete. But, listening for web errors in a console request smells like I'm missing something; ideally I'd like to figure out what the "correct fix" would be here.) 🤔

**Comment by michaelrog** [comment]
Ok, maybe I understand how we got here:

The test for `isConsoleRequest()` may be naive; it's just looking at the `PHP_SAPI` value... And presumably, in the testing context, Craft is getting spun up with its web components, _because the point is to test the system as if it was in the web context_. But `PHP_SAPI` will still indicate that we're in the console, even though we're dealing with the _web_ Application.

If that sounds right so far, then my questions would be:

 - In this case, is there even a Request to resolve at all? (The plugin _assumes_ that `init()` is running in the context of a normal web or console Request... but maybe not? i.e. Maybe we just bootstrapped everything for the sake of testing, but there actually isn't a route in play?)
 - Is there benefit to running New Relic in testing?

If we don't care about New Relic during testing, maybe it's feasible to use the [`disabledPlugins`](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) config item to just disable the New Relic plugin in your testing env?

**Comment by renzoolguin** [comment]
Thanks for the quick replies! Adding the New Relic plugin to the disabledPlugins makes sense. Let me try that approach and report back.

**Comment by renzoolguin** [comment]
Adding `'disabledPlugins' => ['new-relic'],` to "tests/_craft/config/general.php" does the trick. Thanks!

**Comment by michaelrog** [comment]
I [filed this issue w/ Yii](https://github.com/yiisoft/yii2/issues/19096)... The suggestion from over there is:
> You must set 
> ```
> Yii:$app->request->setIsConsoleRequest(Yii:$app->request instanceof yii/console/Request);
> ```
> in test bootstrap.

c.f. Example modification to the default `TestCase` here:
https://github.com/yiisoft/yii2/pull/19101/files

**Comment by WinterSilence** [comment]
@michaelrog it's not "official word", but i'm think [it's can help](https://github.com/yiisoft/yii2/pull/19101/files#diff-abf1fa77a19f720052b75bc802df0260157b9064d8c3c12a80794f01e9acc065)
